# Cобственные примеры для каждого из представленных свойств матричных вычислений.

In [1]:
import numpy as np

## Транспонирование матрицы

Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [4]:
A = np.matrix('12 24 35; 46 57 68; 9 2 1')
print('Исходная матрица:\n', A)
print('Первое транспонирование матрицы:\n', A.T)
print('Второе транспонирование матрицы:\n', (A.T).T)

Исходная матрица:
 [[12 24 35]
 [46 57 68]
 [ 9  2  1]]
Первое транспонирование матрицы:
 [[12 46  9]
 [24 57  2]
 [35 68  1]]
Второе транспонирование матрицы:
 [[12 24 35]
 [46 57 68]
 [ 9  2  1]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [8]:
A = np.matrix('5 7 15; 2 33 11; 3 4 1')
print('Матрица А:\n', A)
B = np.matrix('12 24 35; 46 57 68; 9 2 1')
print('Матрица B:\n', B)

L = (A + B).T
print('Транспонирование суммы матриц:\n', L)

R = A.T + B.T
print('Cуммa транспонированных матриц:\n', R)

Матрица А:
 [[ 5  7 15]
 [ 2 33 11]
 [ 3  4  1]]
Матрица B:
 [[12 24 35]
 [46 57 68]
 [ 9  2  1]]
Транспонирование суммы матриц:
 [[17 48 12]
 [31 90  6]
 [50 79  2]]
Cуммa транспонированных матриц:
 [[17 48 12]
 [31 90  6]
 [50 79  2]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:

In [9]:
A = np.matrix('5 7; 5 33')
print('Матрица А:\n', A)
B = np.matrix('14 32; 14 45')
print('Матрица B:\n', B)

L = (A.dot(B)).T
print('Транспонирование произведения матриц:\n', L)

R = (B.T).dot(A.T)
print('Произведение транспонированных матриц'
      'расставленных в обратном порядке:\n', R)

Матрица А:
 [[ 5  7]
 [ 5 33]]
Матрица B:
 [[14 32]
 [14 45]]
Транспонирование произведения матриц:
 [[ 168  532]
 [ 475 1645]]
Произведение транспонированных матрицрасставленных в обратном порядке:
 [[ 168  532]
 [ 475 1645]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [10]:
A = np.matrix('5 7 8; 2 31 5')
k = 2
print('Исходная матрица:\n', A)

L = (k * A).T
print('Транспонирование произведения матрицы на число:\n', L)

R = k * (A.T)
print('Произведение числа на транспонированную матрицу:\n', R)

Исходная матрица:
 [[ 5  7  8]
 [ 2 31  5]]
Транспонирование произведения матрицы на число:
 [[10  4]
 [14 62]
 [16 10]]
Произведение числа на транспонированную матрицу:
 [[10  4]
 [14 62]
 [16 10]]


Свойство 5. Определители исходной и транспонированной матрицы совпадают:

In [11]:
A = np.matrix('5 7 9; 1 13 7; 7 21 3')
print('Исходная матрица:\n', A)

A_det = np.linalg.det(A)
print('Определитель исходной матрицы:', format(A_det, '.9g'))

A_T_det = np.linalg.det(A.T)
print('Определитель транспонированной матрицы:', format(A_T_det, '.9g'))

Исходная матрица:
 [[ 5  7  9]
 [ 1 13  7]
 [ 7 21  3]]
Определитель исходной матрицы: -848
Определитель транспонированной матрицы: -848


##  Действия над матрицами

Умножение матрицы на число

Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [12]:
A = np.matrix('5 7 7; 2 33 7; 1 2 3')
print('Исходная матрица:\n', A)

L = 1 * A
print('Произведение единицы и матрицы:\n', L)

Исходная матрица:
 [[ 5  7  7]
 [ 2 33  7]
 [ 1  2  3]]
Произведение единицы и матрицы:
 [[ 5  7  7]
 [ 2 33  7]
 [ 1  2  3]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [13]:
A = np.matrix('5 7; 2 33')
Z = np.matrix('0 0; 0 0')
print(f"Исходная матрица:\n {A}\n", f"Нулевая матрица:\n {Z}")

L = 0 * A
print('Произведение нуля и матрицы A:\n', L)

Исходная матрица:
 [[ 5  7]
 [ 2 33]]
 Нулевая матрица:
 [[0 0]
 [0 0]]
Произведение нуля и матрицы A:
 [[0 0]
 [0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [14]:
A = np.matrix('5 7 7; 2 33 7; 1 2 3')
print('Исходная матрица:\n', A)
p, q = 5, 7

L = (p + q) * A
print('Произведение матрицы на сумму чисел:\n', L)

R = p * A + q * A
print('Cуммa произведений матрицы на каждое из чисел:\n', R)

Исходная матрица:
 [[ 5  7  7]
 [ 2 33  7]
 [ 1  2  3]]
Произведение матрицы на сумму чисел:
 [[ 60  84  84]
 [ 24 396  84]
 [ 12  24  36]]
Cуммa произведений матрицы на каждое из чисел:
 [[ 60  84  84]
 [ 24 396  84]
 [ 12  24  36]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [15]:
A = np.matrix('5 7 7; 2 33 7; 1 2 3')
print('Исходная матрица:\n', A)
p, q = 5, 7

L = (p * q) * A
print('Произведение матрицы на произведение 2-ух чисел:\n', L)

R = p * (q * A)
print('Произведение 2 числа и матрицы, умноженное на 1 число:\n', R)

Исходная матрица:
 [[ 5  7  7]
 [ 2 33  7]
 [ 1  2  3]]
Произведение матрицы на произведение 2-ух чисел:
 [[ 175  245  245]
 [  70 1155  245]
 [  35   70  105]]
Произведение 2 числа и матрицы, умноженное на 1 число:
 [[ 175  245  245]
 [  70 1155  245]
 [  35   70  105]]


Сложение матриц


Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [16]:
A = np.matrix('5 7; 2 33')
print('Матрица А:\n', A)
B = np.matrix('11 22; 44 55')
print('Матрица B:\n', B)

L = A + B
print('Сложение матрицы А и В:\n', L)

R = B + A
print('Сложение матрицы B и A:\n', R)

Матрица А:
 [[ 5  7]
 [ 2 33]]
Матрица B:
 [[11 22]
 [44 55]]
Сложение матрицы А и В:
 [[16 29]
 [46 88]]
Сложение матрицы B и A:
 [[16 29]
 [46 88]]


Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:

In [17]:
A = np.matrix('5 7; 2 33')
print('Матрица А:\n', A)
B = np.matrix('11 22; 44 55')
print('Матрица B:\n', B)
C = np.matrix('1 3; 3 3')
print('Матрица C:\n', C)

L = A + (B + C)
print('A + (B + C):\n', L)

R = (A + B) + C
print('(A + B) + C:\n', R)

Матрица А:
 [[ 5  7]
 [ 2 33]]
Матрица B:
 [[11 22]
 [44 55]]
Матрица C:
 [[1 3]
 [3 3]]
A + (B + C):
 [[17 32]
 [49 91]]
(A + B) + C:
 [[17 32]
 [49 91]]


Умножение матриц

Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:

In [18]:
A = np.matrix('5 7; 2 33')
print('Матрица А:\n', A)
B = np.matrix('11 22; 44 55')
print('Матрица B:\n', B)
C = np.matrix('1 3; 3 3')
print('Матрица C:\n', C)

L = A.dot(B.dot(C))
print('A*(B*C)=\n', L)

R = (A.dot(B)).dot(C)
print('(A*B)*C=\n', R)

Матрица А:
 [[ 5  7]
 [ 2 33]]
Матрица B:
 [[11 22]
 [44 55]]
Матрица C:
 [[1 3]
 [3 3]]
A*(B*C)=
 [[1848 2574]
 [7051 9999]]
(A*B)*C=
 [[1848 2574]
 [7051 9999]]


Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:

In [20]:
A = np.matrix('5 7; 2 33')
print('Матрица А:\n', A)
B = np.matrix('11 22; 44 55')
print('Матрица B:\n', B)
C = np.matrix('1 3; 3 3')
print('Матрица C:\n', C)

L = A.dot(B + C)
print('Произведение матрицы на сумму матриц:\n', L)

R = A.dot(B) + A.dot(C)
print('Cуммa произведений матриц:\n', R)


Матрица А:
 [[ 5  7]
 [ 2 33]]
Матрица B:
 [[11 22]
 [44 55]]
Матрица C:
 [[1 3]
 [3 3]]
Произведение матрицы на сумму матриц:
 [[ 389  531]
 [1575 1964]]
Cуммa произведений матриц:
 [[ 389  531]
 [1575 1964]]


## Определитель матрицы

Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

In [21]:
A = np.matrix('5 7 4; 2 9 4; 2 1 1 ')
print('Матрица А:\n', A)
print('Транспонированнная матрица А:\n', A.T)

det_A = round(np.linalg.det(A), 3)
print('Определитель исходной матрицы =', det_A)

det_A_t = round(np.linalg.det(A.T), 3)
print('Определитель транспонированной матрицы =', det_A_t)

Матрица А:
 [[5 7 4]
 [2 9 4]
 [2 1 1]]
Транспонированнная матрица А:
 [[5 2 2]
 [7 9 1]
 [4 4 1]]
Определитель исходной матрицы = 3.0
Определитель транспонированной матрицы = 3.0


Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [22]:
A = np.matrix('5 7 4; 0 0 0; 2 1 1 ')
print('Матрица А:\n', A)

print('Определитель матрицы A =', np.linalg.det(A))

Матрица А:
 [[5 7 4]
 [0 0 0]
 [2 1 1]]
Определитель матрицы A = 0.0


Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [23]:
A = np.matrix('9 1 7; 9 6 3; 5 6 1')
print('Матрица А:\n', A)
B = np.matrix('9 1 7; 5 6 1; 9 6 3')
print('Матрица B:\n', B)

print('Определитель матрицы A =', round(np.linalg.det(A), 3))
print('Определитель матрицы B =', round(np.linalg.det(B), 3))

Матрица А:
 [[9 1 7]
 [9 6 3]
 [5 6 1]]
Матрица B:
 [[9 1 7]
 [5 6 1]
 [9 6 3]]
Определитель матрицы A = 66.0
Определитель матрицы B = -66.0


## Обратная матрица

Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [25]:
A = np.matrix('3. -1.; 11. 1.')
print('Матрица А:\n', A)

A_inv = np.linalg.inv(A)
print('Обратная матрица:\n', A)

A_inv_inv = np.linalg.inv(A_inv)
print('Обратная матрица обратной матрицы:\n', A_inv_inv)

Матрица А:
 [[ 3. -1.]
 [11.  1.]]
Обратная матрица:
 [[ 3. -1.]
 [11.  1.]]
Обратная матрица обратной матрицы:
 [[ 3. -1.]
 [11.  1.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [26]:
A = np.matrix('3. -1.; 11. 1.')
print('Матрица А:\n', A)

L = np.linalg.inv(A.T)
print('Обратная матрица транспонированной матрицы:\n', L)

R = (np.linalg.inv(A)).T
print('Транспонированная матрица от обратной матрицы:\n', R)

Матрица А:
 [[ 3. -1.]
 [11.  1.]]
Обратная матрица транспонированной матрицы:
 [[ 0.07142857 -0.78571429]
 [ 0.07142857  0.21428571]]
Транспонированная матрица от обратной матрицы:
 [[ 0.07142857 -0.78571429]
 [ 0.07142857  0.21428571]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [28]:
A = np.matrix('3 1; 5 4')
print('Матрица А:\n', A)
B = np.matrix('1 1; 1 2')
print('Матрица B:\n', B)

L = np.linalg.inv(A.dot(B))
print('Обратная матрица произведения матриц:\n', L)

R = np.linalg.inv(B).dot(np.linalg.inv(A))
print('Произведение обратных матриц:\n', R)

Матрица А:
 [[3 1]
 [5 4]]
Матрица B:
 [[1 1]
 [1 2]]
Обратная матрица произведения матриц:
 [[ 1.85714286 -0.71428571]
 [-1.28571429  0.57142857]]
Произведение обратных матриц:
 [[ 1.85714286 -0.71428571]
 [-1.28571429  0.57142857]]
